apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # The role name
  name: vector-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
